select * from customer;
select * from product;
select * from sales;
select * from customer where city in ('Philadelphia','Seattle');
select * from customer where city = 'Philadelphia' or city = 'Seattle';
select * from customer where age between 20 and 30;
select * from customer where age >= 20 and age <= 30;
select * from sales;
select * from sales where ship_date between '2014-02-10' and '2015-01-10';
select * from customer where customer_name like 'J%';
select * from customer where customer_name like '%Carrol%';
select * from customer where customer_name like '____ %';
select * from customer;
select * from customer where customer_name like '______ P%';
select * from customer where state like 'Cali%' order by customer_name DESC;
select * from customer where city like 'T%' order by customer_id ASC;
select * from customer where  age between 21 and 45 and segment='Home Office' order by customer_name DESC;
select * from customer where age between 10 and 29 and state like 'A%' and segment='Home Office' order by 1 DESC;
select * from customer where age between 10 and 29 and state like 'A%' and segment='Home Office' or segment='Corporate' order by 1 DESC;
select * from customer where age between 10 and 29 and state like 'A%' and segment='Home Office' or segment='Corporate' order by 1 DESC limit 50;